### ISSUE TITLE
Rails 4.1 ActiveSupport MultiJSON

### ISSUE THREAD

**Issue by johnstem** [kputnam/stupidedi#70] opened 2015-12-10 19:30 UTC
I am trying to add stupidedi to my project.

After adding stupidedi, immediately upon logging into my application (I am using Devise) I receive the following error,

ArgumentError - In Rails 4.1, ActiveSupport::JSON.decode no longer accepts an options hash for MultiJSON. MultiJSON reached its end of life and has been removed.

I saw what looked like a similar issue here,
https://github.com/kputnam/stupidedi/issues/67

I removed term-ansicolor and tins from the dependencies. I also tried adding the multi_json gem to the stupidedi gem dependencies. Neither approach fixed the error.

Here is what I could find regarding Rails 4.1 and multijson
http://guides.rorlab.org/4_1_release_notes.html

Thank you for your help with this issue, let me know if you would like any additional information.

**Comment by kputnam** [comment] 2015-12-11 01:09
Can you paste a stack trace and which versions of Devise and ActiveSupport you used? I don't use either Devise or Rails much, so I'm not sure where to begin looking except their source code.

**Comment by alexkyllo** [comment] 2015-12-11 01:37
I got this error as well with Rails 4.1 + stupidedi and without devise. So I don't think devise is related. I thought it was a bug in Rails rather than stupidedi, so I just switched that project to Sinatra instead. In retrospect I think it was a stupidedi + rails 4.1 incompatibility. I can try to reproduce again tonight.

**Comment by alexkyllo** [comment] 2015-12-11 14:42
It's because of stupidedi monkeypatching the hash.present? method.

lib/active_support/json/decoding.rb calls this method and throws an execption:

https://www.omniref.com/ruby/gems/activesupport/4.1.6/symbols/ActiveSupport::JSON/decode#line=20

Here's a stack trace:

Started GET "/" for 127.0.0.1 at 2015-12-11 06:40:26 -0800
Processing by HomeController#index as HTML
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)

ArgumentError (In Rails 4.1, ActiveSupport::JSON.decode no longer accepts an options hash for MultiJSON. MultiJSON reached its end of life and has been removed.):
  activesupport (4.2.4) lib/active_support/json/decoding.rb:21:in `decode'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:397:in `load'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:424:in `deserialize'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:516:in `[]'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/cookie_store.rb:114:in `get_cookie'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/cookie_store.rb:90:in `block in unpacked_cookie_data'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/abstract_store.rb:51:in `stale_session_check!'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/cookie_store.rb:89:in `unpacked_cookie_data'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/cookie_store.rb:83:in `block in extract_session_id'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/abstract_store.rb:51:in `stale_session_check!'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/cookie_store.rb:82:in `extract_session_id'
  actionpack (4.2.4) lib/action_dispatch/request/session.rb:49:in `block in []'
  actionpack (4.2.4) lib/action_dispatch/request/session.rb:48:in `fetch'
  actionpack (4.2.4) lib/action_dispatch/request/session.rb:48:in `[]'
  actionpack (4.2.4) lib/action_dispatch/request/session.rb:70:in `id'
  rack (1.6.4) lib/rack/session/abstract/id.rb:282:in `current_session_id'
  rack (1.6.4) lib/rack/session/abstract/id.rb:288:in `session_exists?'
  actionpack (4.2.4) lib/action_dispatch/request/session.rb:152:in `exists?'
  actionpack (4.2.4) lib/action_dispatch/request/session.rb:172:in `load_for_read!'
  actionpack (4.2.4) lib/action_dispatch/request/session.rb:89:in `[]'
  turbolinks (2.5.3) lib/turbolinks/xhr_headers.rb:33:in `set_xhr_redirected_to'
  activesupport (4.2.4) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.4) lib/active_support/callbacks.rb:164:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:164:in `block in halting'
  activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.4) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.4) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.4) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `call'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.4) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.4) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.12.3) lib/puma/server.rb:541:in `handle_request'
  puma (2.12.3) lib/puma/server.rb:388:in `process_client'
  puma (2.12.3) lib/puma/server.rb:270:in `block in run'
  puma (2.12.3) lib/puma/thread_pool.rb:106:in `call'
  puma (2.12.3) lib/puma/thread_pool.rb:106:in `block in spawn_thread'


  Rendered /home/alex/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (14.1ms)
  Rendered /home/alex/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (6.7ms)
  Rendered /home/alex/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (14.7ms)
  Rendered /home/alex/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (69.6ms)

**Comment by johnstem** [comment] 2015-12-11 15:07
Thank you very much for your quick response! The error I am getting does indeed seem to be the same as what alexkylio has posted.

My devise version is 3.4.1 although given what alexkylio has posted a devise issue seems less likely.

After double checking my gemfile, even though the error message refers to Rails 4.1 I can confirm that my Rails and ActiveSupport versions are both 4.2.4.

The stack trace is below

ArgumentError - In Rails 4.1, ActiveSupport::JSON.decode no longer accepts an options hash for MultiJSON. MultiJSON reached its end of life and has been removed.:
  activesupport (4.2.4) lib/active_support/json/decoding.rb:21:in `decode'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:397:in `load'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:424:in `deserialize'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:516:in `[]'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/cookie_store.rb:114:in `get_cookie'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/cookie_store.rb:90:in `block in unpacked_cookie_data'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/abstract_store.rb:51:in `stale_session_check!'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/cookie_store.rb:89:in `unpacked_cookie_data'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/cookie_store.rb:83:in `block in extract_session_id'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/abstract_store.rb:51:in `stale_session_check!'
  actionpack (4.2.4) lib/action_dispatch/middleware/session/cookie_store.rb:82:in `extract_session_id'
  actionpack (4.2.4) lib/action_dispatch/request/session.rb:49:in `block in []'
  actionpack (4.2.4) lib/action_dispatch/request/session.rb:48:in `[]'
  actionpack (4.2.4) lib/action_dispatch/request/session.rb:70:in `id'
  rack (1.6.4) lib/rack/session/abstract/id.rb:282:in `current_session_id'
  rack (1.6.4) lib/rack/session/abstract/id.rb:288:in `session_exists?'
  actionpack (4.2.4) lib/action_dispatch/request/session.rb:152:in `exists?'
  actionpack (4.2.4) lib/action_dispatch/request/session.rb:172:in `load_for_read!'
  actionpack (4.2.4) lib/action_dispatch/request/session.rb:89:in `[]'
  warden (1.2.3) lib/warden/session_serializer.rb:30:in `fetch'
  warden (1.2.3) lib/warden/proxy.rb:212:in `user'
  warden (1.2.3) lib/warden/proxy.rb:318:in `_perform_authentication'
  warden (1.2.3) lib/warden/proxy.rb:104:in `authenticate'
  warden (1.2.3) lib/warden/proxy.rb:114:in `authenticate?'
  devise (3.4.1) app/controllers/devise_controller.rb:103:in `require_no_authentication'
  activesupport (4.2.4) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.4) lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
  activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.4) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.4) lib/action_view/rendering.rb:30:in `process'
  rack-mini-profiler (0.9.7) lib/mini_profiler/profiling_methods.rb:106:in `block in profile_method'
  actionpack (4.2.4) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.4) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.4) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  rack-mini-profiler (0.9.7) lib/mini_profiler/profiler.rb:276:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'

Let me know if I can provide any more information or assistance with this issue.

**Comment by johnstem** [comment] 2015-12-16 18:52
alexkylio is correct, this does seem to be an issue with the monkey patches of native classes located in the lib folder.

This is an unfortunate problem that does not seem easily fixable. I don't think refinements will be of much use here since they will simply fall out of scope.

http://pchm.co/the-problem-with-refinements-in-ruby/

When using Rails, simply removing the blank? and present? Object patches from the Stupidedi module *seems* to fix the problem for me although it is difficult to know for sure in all cases whether Stupidedi will still function properly.

Also of concern is the try method added to Object and Nil class. I removed these from Stupidedi as well although in this case the functionality as implemented *appears* like it should be equivalent to Rails.

You might consider adding a disclaimer in the Readme for Rails users.

**Comment by kputnam** [comment] 2015-12-17 01:19
@johnstem Thanks for the link, I haven't invested the time to understand how refinements work, so the article helps. I'm hesitant to change hundreds of files to find out it won't fix the problem!

Regarding if using ActiveSupport's methods is safe, I'm with you -- not sure. I actually started by copying a few definitions from ActiveSupport, and didn't want to drag the entire library into the project (funny how that turned out). Of course if you see errors in Rails, somehow the definitions have diverged, but it might not matter to stupidedi.

The best two options I see at this point might be (a) just depend on ActiveSupport -- I think the specs test the monkey patches and they might find any incompatibilities (b) if using refinements doesn't impose a burden on users of Stupidedi, maybe I or someone will find time to add the `using` statement to each file.

From a quick test, it looks like a single change to every file might do the trick, since most files are wrapped by the `module Stupidedi; ....; end` scope:

````ruby
module Stupidedi
   using Stupidedi::Refinements

   ...
end
```

I think your idea about a note for Rails users is great! I'll make the change sometime this week, but if anyone submits a PR with that disclaimer before I get to it, I'll merge it.

**Comment by kputnam** [comment] 2015-12-17 01:30
@alexkyllo Thanks for the details and the stack trace! I'm not sure I have the time to address this, but it's been a lingering problem for a while. I'll spend some time this week to see if either refinements or requiring ActiveSupport (better to have them patch the standard library) are viable options.

If I have the time, I'll also implement the changes, but it's more likely that I'll post a request for someone to contribute a PR. Since my time isn't spent using this library, Rails, or even Ruby anymore, I'm a bit afraid of breaking something with a "fix" without realizing it.

**Closed** 2016-04-15 02:29 UTC
